### ISSUE TITLE
Phone Number starting with 6 for country IN is returning invalid

### ISSUE THREAD

**Issue by akchaudhary6532** [ex-phone-number/ex_phone_number#59]
function called: 
```
{:ok, ph} = ExPhoneNumber.parse("6191805152", "IN")
ExPhoneNumber.is_valid_number?(ph)
```
Expected response: `true`
Current response: `false`

Response from `libphonenumber` : `true`
http://libphonenumber.appspot.com/phonenumberparser?number=6191805152&country=IN

**Comment by akchaudhary6532** [comment]
@josemrb I copied the lated xml from libphonenumber to check and the above case is passing new new xml but several test cases are failing.

**Comment by josemrb** [comment]
@akchaudhary6532 see https://github.com/socialpaymentsbv/ex_phone_number/issues/43#issuecomment-814343990
