### ISSUE TITLE
Return country code from given phone number

### ISSUE THREAD

**Issue by gastonrey** [ex-phone-number/ex_phone_number#68]
Hi, this is a doubt not an issue, I see that the Ruby implementation return the country code from a given phone number, like this:

```
number = GlobalPhone.parse('+1-312-555-1212')
# => #<GlobalPhone::Number territory=#<GlobalPhone::Territory country_code=1 name=US> national_string="3125551212">
```

Does this Elixir implementation return the same? I couldn't get this info, not even in tests.

Thanks!

**Comment by josemrb** [comment]
Hey @gastonrey 

Take a look at the `README.md` file.

```
iex> {:ok, phone_number} = ExPhoneNumber.parse("044 668 18 00", "CH")
{:ok,
 %ExPhoneNumber.Model.PhoneNumber{
   country_code: 41,
   country_code_source: nil,
   extension: nil,
   italian_leading_zero: nil,
   national_number: 446681800,
   number_of_leading_zeros: nil,
   preferred_domestic_carrier_code: nil,
   raw_input: nil
}}
```

If `parse` is successful, it returns a tuple `{:ok, %ExPhoneNumber.Model.PhoneNumber{}}`.

`%ExPhoneNumber.Model.PhoneNumber{}` struct contains a `country_code` field.
