### ISSUE TITLE
mix task to update metadata is not available

### ISSUE THREAD

**Issue by lolo-frank** [ex-phone-number/ex_phone_number#79]
ex-phone-number was installed via `mix.exs` using `{:ex_phone_number, "~> 0.4"}`. The documentation states that the metadata can be updated by running `mix update_metadata` however this command is not available.

```elixir
iex> mix update_metadata
** (Mix) The task "update_metadata" could not be found
```

The command is not listed when running `mix help`. Is the task for development purposes or should be be available for all installs?

Thanks!

**Comment by szymon-jez** [comment]
This Mix task is only for development. Please see https://hexdocs.pm/ex_phone_number/readme.html#development. If you have found it referenced in another place of the documentation or think that the documentation can be supported then a comment or a PR are very welcome.
